.TH powersupplies 1 "Power supply calculator" "Pozsar Zsolt" "Power supply calculator"
.SH NAME
Power Supplies \- Power supply calculator application
.SH SYNOPSIS
.B powersupplies [-h | --help | -o | -offline | -v | --version]
.SH DESCRIPTION
This software  is a power supply calculator application.
  OS support: FreeBSD, Linux and Windows.
.PP
Language support: English and Hungarian.
.TE
.SH OPTIONS
.TP
.B \-h \-\-help
Write useable parameters.
.TP
.B \-o \-\-offline
Switch to off-line operation mode.
.TP
.B \-v \-\-version
Write version and build information.
.SH HELP SYSTEM
Online help information is provided as a set of HTML text files.
.PP
This programme uses external application (web browser) to display help.
.SH EXIT STATUS
.TP
.B 0
Successful program execution.
.TP
.B >0
An error has occurred.
.SH VERSION
This applications version is 0.4.1
.SH AUTHOR
Produced by Pozsar Zsolt.
.TS
tab (#);
l l.
\fBHomepage:\fR#http://www.pozsarzs.hu/en/
\fBE-mail:\fR#pozsarzs\@gmail.com
.TE
.TP
Copyright (c) 2011-2016 Pozsar Zsolt
