#!/bin/sh
set -e
# Automatically added by dh_installdocs
if [ "$1" = "configure" ]; then
  if [ -d /usr/doc -a ! -e /usr/doc/power_supplies -a -d /usr/share/doc/power_supplies ]; then
    ln -sf /usr/share/doc/power_supplies /usr/doc/power_supplies
  fi
fi
if [ -x update-menus ]; then
  update-menus
fi
# End automatically added section
